server:
  port: 8070

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: ${COMPUTERNAME:localhost}
 
spring:
  application:
    name: spring-gateway
  cloud:
    gateway:
     routes:
      - id: bankService
        uri: lb://BANKSERVICE
        predicates:
        - Path=/bank/***
      - id: customerService
        uri: lb://CUSTOMERSERVICE
        predicates:
        - Path=/customer/***  
      - id: bankAccountService
        uri: lb://BANKACCOUNTSERVICE
        predicates:
        - Path=/bankAccounts/*** 
      - id: creditService
        uri: lb://CREDITSERVICE
        predicates:
        - Path=/credits/*** 

